# Generated by Django 3.2.17 on 2023-04-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme11', '0004_auto_20230404_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=50)),
                ('tutor_username', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('No Response', 'No Response'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='No Response', max_length=15)),
            ],
        ),
    ]
