# Generated by Django 3.2.17 on 2023-04-16 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme11', '0005_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
