# Generated by Django 4.1.7 on 2023-04-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorme11", "0006_request_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorme_user",
            name="enrolled_classes",
            field=models.ManyToManyField(
                related_name="tutorme_users", to="tutorme11.class"
            ),
        ),
    ]
