# Generated by Django 4.1.7 on 2023-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorme11", "0007_tutorme_user_enrolled_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="catalog_nbr",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="class",
            name="class_section",
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="class",
            name="component",
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="class",
            name="descr",
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="class", unique_together={("catalog_nbr", "class_section")},
        ),
        migrations.RemoveField(model_name="class", name="class_code",),
        migrations.RemoveField(model_name="class", name="class_name",),
        migrations.RemoveField(model_name="class", name="users",),
    ]
