# Generated by Django 4.1.7 on 2023-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorme11", "0008_class_catalog_nbr_class_class_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="catalog_nbr",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_section",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="component",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="descr",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
