# Generated by Django 4.1.7 on 2023-04-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tutorme11",
            "0009_alter_class_catalog_nbr_alter_class_class_section_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="catalog_nbr",
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="class",
            name="class_section",
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="class",
            name="component",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="class",
            name="descr",
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
