# Generated by Django 3.2.17 on 2023-04-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme11', '0012_auto_20230417_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorme_user',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tutorme_user',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
