# Generated by Django 3.2.17 on 2023-04-21 18:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme11', '0013_auto_20230420_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorme_user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('subject', 'catalog_nbr')},
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='class',
            name='component',
        ),
    ]
